### ISSUE TITLE
Syntax highlighting problem

### ISSUE THREAD

**Issue by arthurvr** [grayghostvisuals/transformicons#15]
Right now, In the docs the html code is tagged as `markup`. For example, in https://github.com/grayghostvisuals/transformicons/blob/master/docs/transformicons.md.

This is kind of a problem, because github only recognises `html` and `prism.js` only recognises `markup`. This is also the reason syntax highlighting is broken in the github view of the docs.

I first want to hear your ideas, but I could definitely fix this in the docs task? Going to work on this a bit later.

**Comment by grayghostvisuals** [comment]
Hey Arthur if you can still fix this without removing Prism I'm down.
