### ISSUE TITLE
Hosting for NodeJS

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#24]
Below is a link to a list of hosting options concerning NodeJS applications. Some are free and some are not. We need something free and we definitely need to host the project on a NodeJS capable server as we're doing a Sass conversion to CSS on the server side.

**List**
[https://github.com/joyent/node/wiki/node-hosting](https://github.com/joyent/node/wiki/node-hosting)

Openshift seems like a good option so far
[https://www.openshift.com/products/pricing](https://www.openshift.com/products/pricing)

**Comment by janpaepke** [comment]
silly question but you did run `npm install` first, right?

**Comment by jfroffice** [comment]
@grayghostvisuals I did not try heroku for now.

Maybe
```
npm install -g gulp

or

npm install gulp-cli
```

Other people might had encountered the same issue.

**Comment by grayghostvisuals** [comment]
I finally got things sorted out and working on Heroku. You should be able to see a preview here [https://warm-wildwood-3872.herokuapp.com](https://warm-wildwood-3872.herokuapp.com)

The builder is not currently working however. @jfroffice Since you write the majority of the builder do you have any thoughts? You could try with a free account on your end for Heroku if you'd like. I can surely walk you through steps required.

**Comment by grayghostvisuals** [comment]
Not sure if this is related to the above, but thought it might be helpful. Article discussing worker processes for background jobs which might be what our case is in need of [https://devcenter.heroku.com/articles/asynchronous-web-worker-model-using-rabbitmq-in-node](https://devcenter.heroku.com/articles/asynchronous-web-worker-model-using-rabbitmq-in-node)

**Comment by jfroffice** [comment]
@grayghostvisuals

Maybe one gulp plugin failed like $.exec(..). Do you have some logs ?

I might have a look later in the week.

**Comment by grayghostvisuals** [comment]
I would use the master branch and run ``npm start`` to compile then exit and run ``foreman start web`` which uses the node server that mimics what's on Heroku.

**Comment by jfroffice** [comment]
OK, that's the point. :+1: 

I think we need to edit ProcFile with something like this.
```
web: gulp prod
```
And create a new task called __prod__ which will be moreless like gulp task __serve__ but without $.exec and maybe some other stuff.

**Comment by grayghostvisuals** [comment]
@JordanForeman So I tried many variations in the Procfile and none are working as of now. Most of the ways I've tried can be seen in the commit log for the commits on Jan 8, 2015.

**Comment by JordanForeman** [comment]
@grayghostvisuals I saw that. If you're not too burned out on that approach, I have one last suggestion:

`web: node node_modules/gulp/bin/gulp`

**Comment by grayghostvisuals** [comment]
@JordanForeman Yup, tried it that way and still no luck. I think the gulp server can't run with Heroku and needs the node based server (web.js) in order to run a server. If you wanna try for yourself on a free Heroku account and get it working you will get all the moneys ;)

**Comment by JordanForeman** [comment]
@grayghostvisuals I'll see if I can find more time later today to find a
working solution. Glad we could at least pinpoint the problem though!

On Thu, Jan 8, 2015 at 12:05 PM, Dennis Gaebel <notifications@github.com>
wrote:

> @JordanForeman <https://github.com/JordanForeman> Yup, tried it that way
> and still no luck. I think the gulp server can't run with Heroku and needs
> the node based server (web.js) in order to run a server. If you wanna try
> for yourself on a free Heroku account and get it working you will get all
> the moneys ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grayghostvisuals/transformicons/issues/24#issuecomment-69221312>
> .
>



-- 
Jordan Foreman | thejordanforeman@gmail.com | jordanforeman.com | *cleerly.co
<http://cleerly.co>* | @jordanforeman <http://twitter.com/jordanforeman> |
641-202-3320

**Comment by grayghostvisuals** [comment]
The builder issue has been filed with Heroku support [https://help.heroku.com/tickets/209454](https://help.heroku.com/tickets/209454). If you have a Heroku account you can view the ticket. I can also add collaborators to Heroku for the project on my end so let me know which email to use for you all.

Also to add that what we're trying to achieve is [totally doable with Heroku](https://twitter.com/gryghostvisuals/status/552167600684531713). We just need to determine if we can still run on a free plan or not.

**Comment by grayghostvisuals** [comment]
I just want to say this issue has been a pleasure, but I'm super excited to say we have lift off Houston and here's the fix for the insanely curious. Also huge thanks to @hunterloftis for the super quick support on this. Welcome to Heroku everyone. :fireworks: 

```javascript
gulp.task('prod', function() {
  $.connect.server({
    root: [paths.site],
    port: process.env.PORT || 5000,
    livereload: false,
    middleware: function(connect) {
      return [
      connect().use(connect.query()),
      connect().use(builder.middleware())
      ];
    }
  });
});
```

![tumblr_inline_misrk5wrf81qz4rgp](https://cloud.githubusercontent.com/assets/934322/5674546/41b12b3a-977a-11e4-9187-31c892f219bc.gif)

**Comment by hunterloftis** [comment]
:tada:
