### ISSUE TITLE
Provide transformicons JS method call for builds.

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#28]
This code snippet below needs to be provided on builds otherwise users think the demos they pasted the code for are broken when you click and they won't transform.

```javascript
transformicons.add('.tcon');
```

**Comment by jfroffice** [comment]
:+1:

**Comment by grayghostvisuals** [comment]
[boom](https://github.com/grayghostvisuals/transformicons/commit/1d3383140265919ade0c654632b14e66b6bc09df)
