### ISSUE TITLE
Also Include SVG

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#29]
I think including SVG in this project is a must. Need to reword things slightly so that SVG is conveyed as something supported with this project.

**Comment by janpaepke** [comment]
to be honest one of the things I think is great about this project is that we can do Icons were people THINK it's based on SVGs but in fact it's pure CSS.
So maybe the wording should reflect that more clearly... as in "using pure CSS and/or SVG" or smth.
