### ISSUE TITLE
Package Builder

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#3]
via [lazyweb-requests #163](https://github.com/h5bp/lazyweb-requests/issues/163#issuecomment-59624864)
@arthurvr Here's the start for the discussion on a builder.
I was thinking Yeoman for this project as the base, but I'm all ears for a discussion on diff approaches.

**Comment by grayghostvisuals** [comment]
@jfroffice We're ready for markup generation now that everything holding us up has been solved. :metal: LMK if you have any questions with the new setup

**Comment by jfroffice** [comment]
@grayghostvisuals sounds good.

I start building simple button markup.

For an extended layout, we can do better and maybe review the __builder.hbs__ in order to use a button layout.

new PR soon :smile:

**Comment by grayghostvisuals** [comment]
Happy to close this issue finally. Thanks for all the efforts everyone especially @jfroffice. Much toasting all around :beers: 
![lemondance](https://cloud.githubusercontent.com/assets/934322/5696619/f061a048-99a4-11e4-8acc-5a6e29a79ef7.gif)
