### ISSUE TITLE
Make Site Responsive.

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#31]
Yes…it's on the list.

**Comment by merodriguezblanco** [comment]
l would like to take this one!

**Comment by grayghostvisuals** [comment]
Great. Just an FYI I plan to lazylaod contributors avatars at the bottom and possibly remove them completely for smaller screens.

On another note this is a tool primarily for developers on desktop so it might be a good idea to just remove the builder nav for responsive situations? Frankly I feel making this responsive is not a breaking need but I'm up for arguments against my take.

**Comment by merodriguezblanco** [comment]
Great! I'll work on some responsive improvements on [this branch](//github.com/merodriguezblanco/transformicons/tree/responsive-site).

I thought on removing the contributors avatars for widths < 768px.

**Comment by merodriguezblanco** [comment]
So, I used three main media queries for the responsive version:

* 768px <= width <= 979px
* width <= 767px
* width <= 480px

The more visible changes are for the width <= 767px. For this width I:

* Hide the contributors section in the footer.
* Hide the build nav link on the header.
* Display the github links, the transformicons and the header links in a list-style way.

You can see the result on [this branch](https://github.com/merodriguezblanco/transformicons/tree/responsive-site). Please, let me know what you think so I can make further changes or just create the pull request.

I was planning to refactor some sass code on a future pull request using sass mixins and variables, so we can make the code DRYer ;)

**Comment by merodriguezblanco** [comment]
@grayghostvisuals please see new pull request #66 
Cheers!

**Comment by K10shah** [comment]
Can i help you on this one ? I am a beginner to git and also web programming but i know the basics well

**Comment by grayghostvisuals** [comment]
@K10shah Appreciate you having the desire to jump in here, but I it's not really beneficial to the project  at this time.
