### ISSUE TITLE
Code Organization

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#33]
The structure is pretty darn close just need to go through the Sass code and finalize naming conventions and usage context for each icon.

**Comment by anselmh** [comment]
If you need help here I think it’d be helpfulto share what kind of help you need and what people could do :)

**Comment by grayghostvisuals** [comment]
@anselmh Yeah agreed. Always in a hurry am I ;)
I actually organized the directory structure how I wanted so all good there. I'm gonna file a new issue with a clearly stated purpose. Much to do.
