### ISSUE TITLE
centralize .js file

### ISSUE THREAD

**Issue by janpaepke** [grayghostvisuals/transformicons#34]
Currently the core lib for transformicons is stored in two locations in the project:

- /dist/transformicons.js
- /site/js/libs/transformicons.js

this might be confusing in the future.
There should be one file located in the source folder that gets copied to the dist folder on build.
Or the other way around.

The point is: There should be one main file.
Maybe the site should use a minified version (generated on build) to avoid confusion?

**Comment by grayghostvisuals** [comment]
agreed.

**Comment by grayghostvisuals** [comment]
I got this taken care of on my end :) :+1:

**Comment by jfroffice** [comment]
:+1:
