### ISSUE TITLE
Builder only works once

### ISSUE THREAD

**Issue by janpaepke** [grayghostvisuals/transformicons#35]
The builder only works the first time you use it.

Reproduce:
- click build
- change javascript radio button to minified
- click build again

nothing new will be generated until you reload the page.

**Comment by grayghostvisuals** [comment]
@jfroffice Any idea on a fix t this?

**Comment by grayghostvisuals** [comment]
Nm. I found the problem. It was caused by Prism dynamically highlighting the textarea elements when we compile to maintain syntax highlighting. I need to find a fix to this but I currently removed it for the moment on my local machine.

**Comment by jfroffice** [comment]
@grayghostvisuals I saw that Prism on network tab was called each time user press build button. ?!?!

No other expertise for now.
