### ISSUE TITLE
Assemble/Template/Layout Errors

### ISSUE THREAD

**Issue by jfroffice** [grayghostvisuals/transformicons#45]
```
npm start

> Transformicons@0.3.2 start /Users/jfroffice/Projects/transformicons
> node node_modules/gulp/bin/gulp

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jfroffice/Projects/transformicons/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:211:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! Transformicons@0.3.2 start: `node node_modules/gulp/bin/gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Transformicons@0.3.2 start script 'node node_modules/gulp/bin/gulp'.
npm ERR! This is most likely a problem with the Transformicons package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/gulp/bin/gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls Transformicons
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jfroffice/Projects/transformicons/npm-debug.log
```

**Comment by grayghostvisuals** [comment]
First you need to be using 0.10 for node as this is the engine specified for Heroku and listed in the package.json file. Try removing and reinstalling and let me know in another issue if that fails.

**Comment by jfroffice** [comment]
OK.

I downgrade node v0.10.36.
I clone your repo.
```
rm -rf ./node_modules/
npm install 
npm start
```
I get this...

![capture d ecran 2015-02-13 a 20 23 45](https://cloud.githubusercontent.com/assets/964701/6193753/ad9fb022-b3be-11e4-8f77-d2ed82a45e04.png)


Strange ?!? any idea, how to fix this.

I am on [master].

**Comment by grayghostvisuals** [comment]
@jfroffice Make sure you have the latest updates from master for me. Something is up on your end.

**Comment by doowb** [comment]
We just pushed up some changes in assemble that might be affecting this. I'm looking into it now.

**Comment by grayghostvisuals** [comment]
@doowb Thanks for the heads up. I did change the directory structure a bit so I'm not sure if he's experiencing something with assemble or because he does not have the latest changes.

**Comment by doowb** [comment]
It's an assemble/template/layout issue. I tracked it down. Just need to fix it.

**Comment by grayghostvisuals** [comment]
@doowb nice! thanks for the spot. let me know when it's fixed :)

**Comment by doowb** [comment]
Fixed, get the latest dependencies with `rm -fr node_modules && npm cache clear && npm i`

**Comment by jonschlinkert** [comment]
this was all me folks. my apologies for any troubles this has caused. let us know if you have any more issues. (and thanks @doowb!)

**Comment by grayghostvisuals** [comment]
Thanks gents! No worries just glad we caught it early :)

@jfroffice This should be working now, but let us know before I close the issue.

**Comment by grayghostvisuals** [comment]
I just verified things myself. This should all be good now :metal: Thanks again for the help gang

**Comment by jfroffice** [comment]
@grayghostvisuals it is also working on my side. Great ! thanks @doowb.

Any way to use a tag on package.son ?
```
"dependencies": {
    "assemble": "git://github.com/assemble/assemble#v0.6.0",
    ....
}
```

What is release perspective for [assemble](https://github.com/assemble/assemble) ? @doowb @jonschlinkert
