### ISSUE TITLE
Builder does not include all necessary styling

### ISSUE THREAD

**Issue by denoir** [grayghostvisuals/transformicons#50]
**Reproducing the issue**
- [Open the builder](http://www.transformicons.com/builder.html)
- Select nothing but "Menu to X (Crossover Style)"
- Select "CSS"
- Choose unminified Javascript
- Click Build

**Expected outcome**
Receiving complete CSS and JS source required to set up the selected icon in my project.

**Actual outcome**
Only structural CSS is returned, no specific styling for the selected icon:

    .tcon {
      appearance: none;
      border: none;
      cursor: pointer;
      display: -webkit-flex;
      display: -ms-flexbox;
      display: flex;
      -webkit-justify-content: center;
      -ms-flex-pack: center;
      justify-content: center;
      -webkit-align-items: center;
      -ms-flex-align: center;
      align-items: center;
      height: 40px;
      transition: 0.3s;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
      width: 40px;
      background: transparent; }
      .tcon > * {
        display: block; }
      .tcon:focus {
        outline: none; }

    .tcon-visuallyhidden {
      border: 0;
      clip: rect(0 0 0 0);
      height: 1px;
      margin: -1px;
      overflow: hidden;
      padding: 0;
      position: absolute;
      width: 1px; }
      .tcon-visuallyhidden:active, .tcon-visuallyhidden:focus {
        clip: auto;
        height: auto;
        margin: 0;
        overflow: visible;
        position: static;
        width: auto; }

**Additional notes**
When selecting SASS the `tcon-menu-lines` mixin is included in the source.
When selecting another icon (i.e. "Menu to X (Butterfly Style)") the class `tcon-menu__lines` is included in the source (also in the CSS source).

**Comment by grayghostvisuals** [comment]
Yup. Thanks for the catch. I'm currently working on the fix. A few files are not being referenced in our dependency index.

**Comment by denoir** [comment]
Builder works as expected now, thank you!

**Comment by denoir** [comment]
Builder works as expected now, thank you!

**Comment by grayghostvisuals** [comment]
@denoir np :palm_tree:
