### ISSUE TITLE
CommonJS compat?

### ISSUE THREAD

**Issue by tnguyen14** [grayghostvisuals/transformicons#56]
I tried to build JS from the website, download it and include it in my project using browserify. However, I got the following error `Uncaught ReferenceError: transformicons is not defined`. The doc mentions that this uses UMD, which I assumed would be compatible with CommonJS. Am I doing something wrong here? Is there a way to use this with browserify/CommonJS environment?

**Comment by grayghostvisuals** [comment]
We built the JS to be AMD compatible although I personally don't use commonJS. Can you provide me with an example of your setup so I can test myself?

**Comment by tnguyen14** [comment]
I paste the JS code into a file called `transformicon.js`, then in my main `app.js`, I require it like so
```js
require('./transformicons.js');
```
then run browserify on `app.js`.

I am not sure what is required to set up, but instead of appending the line `transformicons.add('.tcon');` at the end of the file, perhaps it could be used like this?
```js
var transformicons = require('./transformicons');
transformicons.add('.tcon');
```

**Comment by grayghostvisuals** [comment]
@tnguyen14 Are you saying we need to remove the ``transformicons.add('.tcon');`` call that we include by default for the builder?

**Comment by tnguyen14** [comment]
@grayghostvisuals I am not very familiar with the structure of the code, so I'm not sure the purpose of it, or why you need to expose it on the global scope as mentioned on your docs.

You can use this wrapper to make it compatible with both AMD and CommonJS https://github.com/umdjs/umd/blob/master/returnExports.js#L41, or this to expose to the global scope https://github.com/umdjs/umd/blob/master/returnExportsGlobal.js

**Comment by tnguyen14** [comment]
Update: I've tried using the `returnExports` and have it worked great with browserify. Basically, I just removed the line `transformicons.add('.tcon');` from the built file.

Then I used the snippet I suggested before, and it works well.
```js
var transformicons = require('./transformicons');
transformicons.add('.tcon');
```

I think that if you use `returnExportsGlobal` to export it to a global variable if neither AMD and CommonJS is used, then it would work in all cases. You just need to update the document to include a **manual** step of including the line `transformicons.add('.tcon');` in any of the 3 environments.

This is quite simple, and if you'd like I'm more than happy putting together a PR for it.

**Comment by grayghostvisuals** [comment]
> Are you saying we need to remove the transformicons.add('.tcon'); call that we include by default for the builder?

This is exactly what I had originally asked. We can put a checkbox in that states to place the call in the built file or not or just not do it entirely? Not sure on that part yet.

**Comment by tnguyen14** [comment]
Personally I think that line should be written manually, so it is consistent across all environments (seems to be the approach taken on the website too?). But that will mean a breaking change to the library. Perhaps there's a way to do it automatically somehow with JS, but I am not sure.

**Comment by tnguyen14** [comment]
In addition to remove that line, I think you need to update the UMD wrapper to use `returnExportsGlobal` too I believe.

**Comment by grayghostvisuals** [comment]
@janpaepke Thoughts on what @tnguyen14 points out?

**Comment by janpaepke** [comment]
Yes, that is true. Although I am still not quite sure why we would need a CommonJS export, as this is a front end module.
How is this useful outside of the browser?
Maybe someone can clarify?

**Comment by tnguyen14** [comment]
I disagree with that. CommonJS is widely used these days in the browser, thanks to compiler tools like browserify and webpack. In fact, many devs (including me) have been using npm as the main tool for package management for the browsers.

**Comment by janpaepke** [comment]
That was the explanation I was hoping for. So I agree, let's add CommonJS.

**Comment by janpaepke** [comment]
Please test and feel free to merge into master, if everything works.

**Comment by tnguyen14** [comment]
:+1:

**Comment by grayghostvisuals** [comment]
@tnguyen14 Do the docs need updating for this adjustment?
