### ISSUE TITLE
What do the toggles/switches do?

### ISSUE THREAD

**Issue by kennedysgarage** [grayghostvisuals/transformicons#58]
![screen shot 2015-02-20 at 1 41 10 pm](https://cloud.githubusercontent.com/assets/183007/6306994/2757b86e-b906-11e4-8f79-dc9d3e6d701b.png)

**Comment by grayghostvisuals** [comment]
Green turns them on. Not making sense?

**Comment by kennedysgarage** [comment]
Turns what on? If I click them they still work.

**Comment by kennedysgarage** [comment]
Ohhh, you can select which ones you want to build.

**Comment by grayghostvisuals** [comment]
Maybe a little note to users? We'll think on that

**Comment by kennedysgarage** [comment]
I thought I was looking at the home page because I taped in from your [tweet](https://twitter.com/gryghostvisuals/status/568841621611126785) and didn't know I was in build mode. It makes a lot more sense now. Keep up the amazing work!
