### ISSUE TITLE
Minus/ remove icon

### ISSUE THREAD

**Issue by tnguyen14** [grayghostvisuals/transformicons#59]
Could I request icons here?

It'd be nice to have a remove icon that transform to the checkbox - similar to how the add icon is right now.

**Comment by grayghostvisuals** [comment]
Yep definitely. Thanks for the suggestion.

**Comment by merodriguezblanco** [comment]
@grayghostvisuals , @tnguyen14  I've been working on a remove checkbox similar to the add icon. You can check it on #67 .

Please let me know what you think!
