### ISSUE TITLE
New Static Site Generator

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#69]
We need to find a new static site generator with great community involvement and support. Project must be well maintained, have top notch documentation and be node based.

- [ ] http://hexo.io
- [ ] https://github.com/segmentio/metalsmith

**Comment by gosupernova** [comment]
May I suggest Jekyll, http://jekyllrb.com/

I know you mentioned being node based but you can implement it with node & grunt so you can get a slick pipeline done along with live reload etc

**Comment by grayghostvisuals** [comment]
@gosupernova What about for gulp?

**Comment by gosupernova** [comment]
I have not used it (yet) but it looks like it does

https://www.npmjs.com/package/gulp-jekyll

**Comment by grayghostvisuals** [comment]
That's a little too new for my taste unfortunately :( but thanks for leaving it here in case for reference.
