### ISSUE TITLE
Use a better Sass compiler

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#70]
Currently we're using node-sass to compile bit it's been kind of letting me down in terms of it's ability. What is better than node-sass?

**Comment by arthurvr** [comment]
`node-sass` is official and the most complete. Ruby sass, which is terrible slow and would add another dependency, is the only alternative we have.

**Comment by grayghostvisuals** [comment]
yup. my bad. node-sass it is still.
