### ISSUE TITLE
iOS 8.1.3 buggy burger-icon 

### ISSUE THREAD

**Issue by Worstkaes** [grayghostvisuals/transformicons#71]
Hey,

I'm using transformicons for my burger-icon and it does not work well on iOS 8.1.3 iPhone 6. On the screenshot of my menu, you see the "opened" version of the icon.
I also tried to have a look on the icons on your page, but the burger-icons are not visible on my phone. Are there any issues with iOS 8.1.3? 

I'm using the third one from this page: http://www.transformicons.com/builder.html

My "opened" menu-icon:
![img_0830](https://cloud.githubusercontent.com/assets/6573138/6896261/c3d8c7ea-d6e9-11e4-9690-c81565510019.jpg)

The demo-page on my iPhone 6 (iOS 8.1.3 Safari):
![img_0829](https://cloud.githubusercontent.com/assets/6573138/6896249/a37db532-d6e9-11e4-99f7-89cd08246598.PNG)

**Comment by Worstkaes** [comment]
Now I've used the CSS-File instead Sass and it works fine. Maybe missed the Sass-File an update?

**Comment by grayghostvisuals** [comment]
@Worstkaes So you went to the builder on the official site and tried to use the Sass compiled code? I'm slightly confused here.

**Comment by Worstkaes** [comment]
Yep, sorry for the confusion. I used the builder on the official site.

**Comment by grayghostvisuals** [comment]
The site isn't responsive at the moment and those rows use flexbox so getting more narrow in viewport width squeezes the containers which are using flexbox tightly. :)

**Comment by Worstkaes** [comment]
Yeah, but I got the issue at my website. After clicking the burger-icon it only transforms to an "one-liner".
I made a fiddle for this: http://jsfiddle.net/pL8b0nqx/3/

Below you see the screenshot from my phone after clicking the burger-icon:
![img_0831](https://cloud.githubusercontent.com/assets/6573138/6897931/fb8274f4-d6f6-11e4-9e74-83dca373e932.jpg)

**Comment by grayghostvisuals** [comment]
Yup. I got it now. I'll look into this more so I can find the root of the cause here. Thanks for the catch.

**Comment by Worstkaes** [comment]
Nice, sorry for my crappy explanation. Next time I make a fiddle immediately. :)

**Comment by grayghostvisuals** [comment]
I just used the builder on the site and didn't come across what you've shown in that fiddle. I didn't have time to inspect why you're fiddle is breaking, but either way this is working as it should. Here's the test case from the produced code I got [http://codepen.io/grayghostvisuals/full/f9a64f0611bdb5f448c81cea26b942cc/](http://codepen.io/grayghostvisuals/full/f9a64f0611bdb5f448c81cea26b942cc/) 

Let me know if you see differently.

**Comment by Worstkaes** [comment]
This code works. But like I said: the css-file version works, the sass don't. Maybe you also used the css-version?

**Comment by grayghostvisuals** [comment]
@Worstkaes I used the builder for **CSS and Sass** output for testing. Please try again as I think you might be mistaken.

**Comment by Worstkaes** [comment]
I made a new fiddle with the following properties in the Transformicons Builder (http://www.transformicons.com/builder.html): 
- third burger-icon from the left 
- Styles: Sass 
- Javascript: unminified
http://jsfiddle.net/pL8b0nqx/4/

I got still the same issue on my iPhone 6 iOS 8.1.3 and also on an iPad 4 iOS 7.0.2:
After clicking the burger-icon it transforms to one-line in the middle, like the screenshot from above. 

Are you testing it on an iOS-Device? Everywhere else it works fine.

**Comment by grayghostvisuals** [comment]
@Worstkaes You need to remove this line from your JS

```javascript
$('#menu_button').click(function(){
   $(this).toggleClass('tcon-transform');
});
```

and add this line instead

```javascript
transformicons.add('.tcon');
```

The reason is the handler is already set for you within the main library so in your original code you were setting another click handler on top of the one already in place. If you look at the docs again you will see this part noted.

**Comment by Worstkaes** [comment]
Oh yeah, that was me testing. I changed it here, but still the same bug on iOS: http://jsfiddle.net/pL8b0nqx/5/

**Comment by grayghostvisuals** [comment]
@Worstkaes So I just did everything you've told me to do and updated my isolated case with your exact code that I copied and pasted from the JSfiddle you keep linking to [http://jsfiddle.net/pL8b0nqx/5/](http://jsfiddle.net/pL8b0nqx/5/). I can only test on iOS simulator ATM for 8.2 + Browserstack for Version 8.0 (550.1) and still not seeing your bug. I'm guessing something is weird with the JSFiddle service itself. Please make another reduced case using a different service like I've done with the CodePen deom here using your JSFiddle code [http://codepen.io/grayghostvisuals/full/f9a64f0611bdb5f448c81cea26b942cc/](http://codepen.io/grayghostvisuals/full/f9a64f0611bdb5f448c81cea26b942cc/)

**Comment by Worstkaes** [comment]
I'm really sorry, but I don't think the fiddle-service is the problem. I used again your builder and made the following example by compiling your sass. I still think, there is only a bug in your sass file, because the normal css works fine. 
I tested it on three different iOS Devices with different iOS Versions. Everywhere the same error.
http://th8853-web449.vorschau.server14.tophoster.de/transformicons/

**Comment by grayghostvisuals** [comment]
> I used again your builder and made the following example by compiling your sass

What are you using to compile Sass on your end? Please also list the following…

1. Browser, version and OS you used with the tcons builder
2. Results form my request below

Also can you double check on your end with the pen I've been sending you please [http://codepen.io/grayghostvisuals/full/f9a64f0611bdb5f448c81cea26b942cc/](http://codepen.io/grayghostvisuals/full/f9a64f0611bdb5f448c81cea26b942cc/)?

**Comment by Worstkaes** [comment]
Hi,
yesterday I used quick&dirty the command-line for compiling with Sass 3.4.9. 
For the tcons builder I used Chrome 41.0.2272.104 / Mac OS X 10.10.2.
Your link (http://codepen.io/grayghostvisuals/full/f9a64f0611bdb5f448c81cea26b942cc/) works fine on my iOS. Did you do something different?

**Comment by grayghostvisuals** [comment]
@Worstkaes No I did not do anything different. Please read my prior comments to you. That code is the same code you gave me. Sorry to say but I'm not seeing this as an issue any longer.
