### ISSUE TITLE
Bug Submission Requirements

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#72]
Add these items to the README in their own section called “Before Filing a Report”

- [ ] Make an isolated demo
- [ ] List your setup and explain in detail the steps to follow in order to reproduce your bug.

**Comment by merodriguezblanco** [comment]
Hi @grayghostvisuals, I can take this one. Where would you like this section to be displayed?

I have also noticed a typo under the `Transformicons Specs`, it currently says `If your Transformicon is truly is a ...`, and it should read `If your Transformicon is truly a ...`.

Please let me know your thoughts before I create the PR.

**Comment by grayghostvisuals** [comment]
@merodriguezblanco Sounds good to me. Section can be somewhere in regards to contributing :)

**Comment by merodriguezblanco** [comment]
@grayghostvisuals  this issue can be closed now ;)
