### ISSUE TITLE
Icon size scaling

### ISSUE THREAD

**Issue by tnguyen14** [grayghostvisuals/transformicons#74]
When I change the `$tcon-size` variable in SASS, for eg. `$tcon-size: 20px`, the size of the actual icon is still the original larger size.

Specifically, I'm using the remove icon, and I can see in the code that its width and height is defined as `width: 34px;` and `height: 10px`. Should this size be scaled according to `$tcon-size`?

**Comment by grayghostvisuals** [comment]
That icon was submitted by @merodriguezblanco so maybe he can make the adjustment for you.

**Comment by merodriguezblanco** [comment]
Hi @tnguyen14  , this happens for all the add icons because the width and height are hardcoded. When I created the remove icon, I followed this convention.

@grayghostvisuals I think it would be a good idea for these icons to be resizable, is this something that we want to support?

**Comment by grayghostvisuals** [comment]
I wonder if this is better handled through a scale transform? Originally I intended it to work as @tnguyen14 is attempting to use it (custom sizing).

**Comment by merodriguezblanco** [comment]
On #75 I started working on scaling the add and remove icons. Let me know what you think about it.

**Comment by grayghostvisuals** [comment]
See commit [bda85ca2e16](https://github.com/grayghostvisuals/transformicons/commit/bda85ca2e16e2706b3a930e8bd4566c683187645)
