### ISSUE TITLE
Remove to arrow right and left icons

### ISSUE THREAD

**Issue by merodriguezblanco** [grayghostvisuals/transformicons#77]
Hi, I've added two more transformicons:

* Remove to left arrow
* Remove to right arrow

You may find them on [this branch](https://github.com/merodriguezblanco/transformicons/tree/remove-arrow-icons), which was checkout from #75 so that both icons scale properly.

@grayghostvisuals  please let me know what you think about them.

Cheers!

**Comment by grayghostvisuals** [comment]
This has been merged in already and can be closed now no?

**Comment by merodriguezblanco** [comment]
Yes, this can be closed. Do you want me to work now on the chevron up to down, and chevron left to right icons?

**Comment by grayghostvisuals** [comment]
sure.
