### ISSUE TITLE
Heroku Barfs for Env.

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#78]
Heroku isn't using the production env when deployed for some reason.

**Comment by grayghostvisuals** [comment]
see Heroku ticket [234255](https://help.heroku.com/tickets/234255)

**Comment by merodriguezblanco** [comment]
Ok, it seems that the "del" module is not being included on the package.json for the production environment (only for the development enviroment).

Heroku was throwing me an ```Error: Cannot find module 'del'```

**Comment by merodriguezblanco** [comment]
Please see #79 and let me know if it works for you.

**Comment by grayghostvisuals** [comment]
Closing because this is sue to gulp-use-min that I have already filed an issue on.
