### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Redsmith24** [grayghostvisuals/transformicons#80]
I tried to make a simple example, but I can't make it work. I used the builder to generate the code for one button-tranform. This is my simple HTML Page:

	<head>
		<meta charset="utf-8" />
		<title>test</title>
		<link rel="stylesheet" href="menue.css" type="text/css" media="screen" charset="utf-8" />
		<script src="menue.js" type="text/javascript"></script>
		<script type="text/javascript"> transformicons.add('.tcon') </script> 
	</head>
	<body>

		<button type="button" class="tcon tcon-menu--xcross" aria-label="toggle menu">
			<span class="tcon-menu__lines" aria-hidden="true"></span>
			<span class="tcon-visuallyhidden">toggle menu</span>
		</button>

	</body>

There is no transforming, when I click the button, nothing happens. What is wrong, can you please give me a hint.

**Comment by grayghostvisuals** [comment]
@Redsmith24 Can you please make a live demo for me to see. There's no way for me to test when you have no assets provided.

**Comment by Redsmith24** [comment]
Yes, no problem:
http://dev.physiotherapie-elmshorn.de/navtest.html

Am 23.04.2015 um 14:49 schrieb Dennis Gaebel <notifications@github.com>:

**Comment by grayghostvisuals** [comment]
@Redsmith24 Since you're loading stuff in the head the call to ``.tcon`` has no idea the DOM even exists yet. Fix is to add async to that script call or move the call before then ending ``body`` tag.

**Option 1**

```html
<head>
    <meta charset="utf-8" />
    <title>test</title>
    <link rel="stylesheet" href="menue.css" type="text/css" media="screen" charset="utf-8" />
    <script src="menue.js" async></script>
    <script async> transformicons.add('.tcon') </script> 
</head>
<body>

    <button type="button" class="tcon tcon-menu--xcross" aria-label="toggle menu">
        <span class="tcon-menu__lines" aria-hidden="true"></span>
        <span class="tcon-visuallyhidden">toggle menu</span>
    </button>

</body>
```

**Option 2**

```html
<head>
    <meta charset="utf-8" />
    <title>test</title>
    <link rel="stylesheet" href="menue.css" type="text/css" media="screen" charset="utf-8" />
</head>
<body>

    <button type="button" class="tcon tcon-menu--xcross" aria-label="toggle menu">
        <span class="tcon-menu__lines" aria-hidden="true"></span>
        <span class="tcon-visuallyhidden">toggle menu</span>
    </button>

    <script src="menue.js"></script>
    <script>transformicons.add('.tcon')</script> 

</body>
```

**Comment by Redsmith24** [comment]
Thank you, very helpful. I'm used to jquery with the ready-function, so I did not consider this point.

**Comment by grayghostvisuals** [comment]
@Redsmith24 In that case you could do this too…

```html
<head>
    <meta charset="utf-8" />
    <title>test</title>
    <link rel="stylesheet" href="menue.css" type="text/css" media="screen" charset="utf-8" />
    <script src="jquery.min.js"></script>
    <script src="menue.js"></script>
    <script>$(document).ready(function() { transformicons.add('.tcon'); });</script>
</head>
<body>

    <button type="button" class="tcon tcon-menu--xcross" aria-label="toggle menu">
        <span class="tcon-menu__lines" aria-hidden="true"></span>
        <span class="tcon-visuallyhidden">toggle menu</span>
    </button>

</body>
```

**Comment by Redsmith24** [comment]
Yes, thank you. In this project, I don't want to use other effetcs, so I don't want to load the jquery-script.

Option1 is not working, because of the async attribut. But there is another attribut that does the job: defer

Both attributes are only useful for external scripts so I integrates the transformicons.add('.tcon') in the external script, call it in the head with the defer attribut and: bingo
;-)

Many thanks.
