### ISSUE TITLE
Can't get example to work

### ISSUE THREAD

**Issue by kyleknighted** [grayghostvisuals/transformicons#83]
I copied over just the Search icon example to codepen and it doesn't seem to work.

http://codepen.io/kyleknighted/pen/WQjWKY

**Comment by grayghostvisuals** [comment]
Add this at the end of the JS lib 

```javascript
transformicons.add('.tcon');
```

This is also listed under the methods section of our docs [http://www.transformicons.com/docs.html](http://www.transformicons.com/docs.html) that will explain how to customize the events.
