### ISSUE TITLE
tcon-remove background color not settable

### ISSUE THREAD

**Issue by tnguyen14** [grayghostvisuals/transformicons#84]
the `background-color` for `tcon-remove` is hard-coded as `black`, is there anyway it can be settable via default, similar to how `tcon-plus` is done `$tcon-plus-color: black !default;`?

**Comment by grayghostvisuals** [comment]
Yep. For now you could create your own custom variable until I push up a fix for this.

**Comment by tnguyen14** [comment]
awesome! thanks!

**Comment by grayghostvisuals** [comment]
Once Heroku doesn't fail it's build to staging env. I can get this live. Sorry for the wait.

**Comment by grayghostvisuals** [comment]
@tnguyen14 This is now live and all set for you to customize. Thanks for being patient :beers:

**Comment by tnguyen14** [comment]
Thank you!! I will try this again as soon as I can and report back.
