### ISSUE TITLE
xcross animation broken in latest Microsoft Edge

### ISSUE THREAD

**Issue by justo** [grayghostvisuals/transformicons#86]
Can be reproduced on [http://www.transformicons.com/](http://www.transformicons.com/) in Edge. Only the xcross transform is incorrect.

![xcross_ms_edge](https://cloud.githubusercontent.com/assets/1137245/12304887/d97b9e0c-b9ff-11e5-871f-2d5f3e73fc44.gif)

MS Edge v25.10586.0.0
MS EdgeHTML 13.10586
Windows 10 Pro v1511

**Comment by grayghostvisuals** [comment]
Any more news on this? Have not had a chance to check the reason why it's not working.

**Comment by WilhelmH** [comment]
This is still a problem in the latest version:
MS Edge 34.14300.1000.0
MS EdgeHTML 14.14300

**Comment by alexdiliberto** [comment]
This is now working on latest Edge, we can close this issue.

Microsoft Edge 38.14393.0.0

![test](https://cloud.githubusercontent.com/assets/666459/23903489/16dc829e-089b-11e7-8c08-ccd03e87005d.gif)

**Comment by grayghostvisuals** [comment]
lol! Those who wait long enough never have to fix the issue. Thanks for the report everyone!
