### ISSUE TITLE
Novice question: how to use transformicon.revert() ?

### ISSUE THREAD

**Issue by voodoo6** [grayghostvisuals/transformicons#89]
Hi,

I'll preface this by saying I have very little javascript knowledge.

I'm using a transformicon on a full page nav menu. When the user clicks the toggle nav button the transformicon animates to the X position and the nav appears. When the user clicks a nav link, I'd like the transformicon to animate back to the initial state.

I have an example here: http://menutester.webflow.io/

1. Reduce the page width until the nav collapses to the transformicon
2. Click the transformicon to show the menu
3. Click a link in the nav

Notice how the transformicon remains in the X state.

Using Jquery (probably easiest for me!) – how do I make the transformicon change back to the initial state when a nav link is clicked?

$(".initial-nav-link").click(function(){
  ?????
});

Apologies in advance for asking what is probably very rudimentary!

**Comment by grayghostvisuals** [comment]
This is what u need to do.

```javascript
$(".initial-nav-link").click(function() {
  transformicons.revert('.tcon')
});
```

**Comment by voodoo6** [comment]
So simple when you know how :)many thanks, it works perfectly.
