### ISSUE TITLE
`deploy` task

### ISSUE THREAD

**Issue by arthurvr** [grayghostvisuals/transformicons#9]
There must be a gulp task to deploy the `site/` directory to `gh-pages`. With that task, some kind of build task should run to:

- Minify HTML/CSS/JS
- Delete unnecessary files (the `.scss` files should not be in the `gh-pages` branch)
- <del>Minify images (we don't have any yet, but those may come)</del>
- <del>Remove unnecessary css rules using https://www.npmjs.org/package/gulp-uncss</del>

This task must run on every commit which effects either the `site/` directory or the `docs/`directory. One possible way to handle that is using travis CI. We could also just run the task locally, but that gets kinda difficult for PRs and commits to not-master branches.

Any additions/feedback? Wanting to work on this this week. 

(The `gh-pages` branch is what will actually get served at `http://transformicons.com` too)

**Comment by grayghostvisuals** [comment]
Just do ``git push heroku master``. I can also set this to run on every push to master via GitHub.

**Comment by jfroffice** [comment]
@grayghostvisuals :beer:
